In [2]:
  from google.colab import drive
  drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.4.1'

In [6]:
dataset = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/ANN with Regression Udemy Deep Learning/Final Folder/Dataset/Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

# Data Preprocessing

#Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
X_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [10]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  12.24,   44.92, 1023.74,   88.21],
       [  27.28,   47.93, 1003.46,   59.22],
       [  17.28,   39.99, 1007.09,   74.25]])

# Building ANN

## Intializing ANN

In [11]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1))

# Part 3 - Training the ANN

## Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Training the ANN model on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 174296.1621
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 584.5953
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 257.1494
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 246.9750
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 241.5552
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 239.0596
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 227.9874
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 215.2374
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 210.4740
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 197.4659
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 187.9422
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

# Predicting the results of the Test set

In [18]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[429.83 431.23]
 [461.28 460.01]
 [464.99 461.14]
 ...
 [471.82 473.26]
 [439.37 438.  ]
 [458.27 463.28]]
